---

- name: Ensure apt packages are present
  apt: name="{{item}}" state=present update_cache=yes cache_valid_time=3600
  with_items:
    - ssh
    - rsync

#- name: Template sysctl.conf to ensure ipv6 disabled
#  template: src="sysctl.conf" dest="/etc/sysctl.conf" backup=yes

- name: Ensure ipv6 disabled in /etc/sysctl.conf
  register: disabled_ipv6
  lineinfile:
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    dest: "/etc/sysctl.conf"
  with_items:
    - line: "net.ipv6.conf.all.disable_ipv6 = 1"
      regexp: "^net\\.ipv6\\.conf\\.all\\.disable_ipv6.*"
    - line: "net.ipv6.conf.default.disable_ipv6 = 1"
      regexp: "^net\\.ipv6\\.conf\\.default\\.disable_ipv6.*"
    - line: "net.ipv6.conf.lo.disable_ipv6 = 1"
      regexp: "^net\\.ipv6\\.conf\\.lo\\.disable_ipv6.*"

- name: Reload sysctl when specified
  when: disabled_ipv6|changed
  shell: /sbin/sysctl -p
  args:
    executable: "/bin/bash"

- name: Ensure /etc/hosts file entry for localhost doesnt contain hostname
  lineinfile:
    line: "127.0.0.1 localhost"
    regexp: "^127\\.0\\.0\\.1.*"
    dest: "/etc/hosts"
