---

- name: Ensure directory is present when zookeeper_download is set to "yes"
  when: zookeeper_download == "yes"
  file:
    path: /opt/src
    state: directory

- name: Create Zookeeper dir
  file:
    path: "{{zookeeper_dir}}"
    state: directory

- name: Download zookeeper version when zookeeper_download is set to "yes"
  when: zookeeper_download == "yes"
  get_url:
    url: "{{zookeeper_url}}"
    dest: "/opt/src/zookeeper-{{zookeeper_version}}.tar.gz"

- name: Unpack tarball
  when: zookeeper_download == "yes"
  command: tar zxf /opt/src/zookeeper-{{zookeeper_version}}.tar.gz --strip-components=1 chdir={{zookeeper_dir}} creates={{zookeeper_dir}}/bin

- name: Unarchive zookeeper package to destination when zookeeper_download is set to "no"
  when: zookeeper_download == "no"
  unarchive:
    src: "{{ zookeeper_archive }}"
    dest: "{{ zookeeper_base_dir }}"
    creates: "{{zookeeper_dir}}/bin"


