---

- name: Apt install required system packages.
  apt: name={{item}} update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - curl
    - wget
    - logrotate
    - ntp

- name: Configure ntp servers
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: Restart ntp
  tags:
    - ntp
    - config
