---

- group: name=kafka system=yes

- user: name=kafka group=kafka system=yes

- name: Change ownership on kafka directory.
  file: path={{kafka_dir}} state=directory owner=kafka group=kafka recurse=yes

- name: Create kafka data folder.
  file: path={{kafka_data}} state=directory recurse=yes owner=kafka group=kafka

- name: Create kafka logs folder.
  file: path={{kafka_logs}} state=directory recurse=yes owner=kafka group=kafka

- name: Kafka Upstart script.
  template: src=kafka.conf dest=/etc/init/kafka.conf

- name: Configure server.properties for kafka
  template: src=server.properties dest={{kafka_conf_dir}}/server.properties owner=kafka group=kafka
  notify: Restart kafka

- name: Configure mirror maker producer properties for kafka
  template: src=mirror-maker-producer.properties dest={{kafka_conf_dir}}/mirror-maker-producer.properties owner=kafka group=kafka
  notify: Restart kafka

- name: Configure mirror maker consumer properties for kafka
  template: src=mirror-maker-consumer.properties dest={{kafka_conf_dir}}/mirror-maker-consumer.properties owner=kafka group=kafka
  notify: Restart kafka

- name: Configure mirror maker init for kafka
  template: src=mirror-maker.conf dest=/etc/init/mirror-maker.conf
  notify: Restart mirror-maker

- name: Start mirror-maker
  when: kafka_mirror_maker_enable == "yes"
  service: name=mirror-maker state=started

- name: Start kafka
  service: name=kafka state=started enabled=yes
