--- 

kafka_servers: 
  hosts: 
    - kafka1.lan
    - kafka2.lan
    - kafka3.lan
  vars: 
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    ansible_ssh_user: vagrant
kafka_wan_servers: 
  hosts: 
    - kafka1.wan
    - kafka2.wan
    - kafka3.wan
  vars: 
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    ansible_ssh_user: vagrant
all: 
  children: 
    - kafka_servers
    - kafka_wan_servers
_meta: 
  hostvars: 
    kafka1.lan: 
      vagrant_cpu: "1"
      vagrant_ip: "192.168.0.21"
      vagrant_mem: "2048"
    kafka2.lan: 
      vagrant_cpu: "1"
      vagrant_ip: "192.168.0.22"
      vagrant_mem: "2048"
    kafka3.lan: 
      vagrant_cpu: "1"
      vagrant_ip: "192.168.0.23"
      vagrant_mem: "2048"
    kafka1.wan: 
      vagrant_cpu: "1"
      vagrant_ip: "192.168.10.21"
      vagrant_mem: "2048"
    kafka2.wan: 
      vagrant_cpu: "1"
      vagrant_ip: "192.168.10.22"
      vagrant_mem: "2048"
    kafka3.wan: 
      vagrant_cpu: "1"
      vagrant_ip: "192.168.10.23"
      vagrant_mem: "2048"