---

- hosts: kafka_servers
  become: yes
  gather_facts: yes
  roles:
    - role: common
    - role: zookeeper
      zookeeper_servers: "{{ groups['kafka_servers'] }}"
    - role: kafka
      kafka_zk_endpoint: "{{ groups['kafka_servers'] | join(':2181,') }}:2181"
      kafka_brokers: "{{ groups['kafka_servers'] }}"
      kafka_host_name: "{{ inventory_hostname }}"
      kafka_version: "0.10.0.1"
      kafka_scala_version: "2.11"
    - role: confluent
      kafka_confluent_archive: "3.0"
      kafka_confluent_version: "3.0.0"
      kafka_scala_version: "2.11"
      kafka_zk_endpoint: "{{ groups['kafka_servers'] | join(':2181,') }}:2181"
      kafka_broker_list: "{{ groups['kafka_servers'] | join(':9092,') }}:9092"
      kafka_control_center_servers: "{{ groups['kafka_servers'] }}"
      #kafka_confluent_hdfs_url: "hdfs://127.0.0.1:2049"
      kafka_confluent_hdfs_url: "hdfs://hadoop1.lan:9000"
      kafka_confluent_hdfs_topics: "test_hdfs"
      kafka_confluent_kafka_rest_id: "kafka-rest-{{ ansible_fqdn }}"
      #kafka_confluent_schema_registry_url: "http://kafka1.lan:8081"
      kafka_confluent_schema_registry_url: "http://127.0.0.1:8081"