---

- hosts: kafka_wan_servers
  become: yes
  gather_facts: yes
  roles:
    - role: common
    - role: oracle-java
      oracle_java_version: "8"
    - role: zookeeper
      zookeeper_version: "3.4.8"
      zookeeper_servers: "{{ groups['kafka_wan_servers'] }}"
    - role: kafka
      kafka_zk_endpoint: "{{ groups['kafka_wan_servers'] | join(':2181,') }}:2181"
      kafka_brokers: "{{ groups['kafka_wan_servers'] }}"
      kafka_host_name: "{{ inventory_hostname }}"
      kafka_version: "0.10.0.1"
      kafka_scala_version: "2.11"
      kafka_mirror_maker_enable: "no"
      kafka_mirror_maker_group_id: "mirror-group2"
      kafka_mirror_maker_producer_bootstrap_servers: "{{ groups['kafka_servers'] | join(':9092,') }}:9092"
      kafka_mirror_maker_blacklist: "blacklisttopic"
#    - role: confluent
#      kafka_confluent_archive: "3.0"
#      kafka_confluent_version: "3.0.0"
#      kafka_scala_version: "2.11"
#      kafka_zk_endpoint: "{{ groups['kafka_wan_servers'] | join(':2181,') }}:2181"
#      kafka_broker_list: "{{ groups['kafka_wan_servers'] | join(':9092,') }}:9092"
#      kafka_control_center_servers: "{{ groups['kafka_wan_servers'] }}"
#      #kafka_confluent_hdfs_url: "hdfs://127.0.0.1:2049"
#      kafka_confluent_hdfs_url: "hdfs://hadoop1.lan:9000"
#      kafka_confluent_hdfs_topics: "test_hdfs"
#      kafka_confluent_kafka_rest_id: "kafka-rest-{{ ansible_fqdn }}"
#      #kafka_confluent_schema_registry_url: "http://kafka1.lan:8081"
#      kafka_confluent_schema_registry_url: "http://127.0.0.1:8081"
