---

- name: Install Java PPA repository
  apt_repository:
    repo: "{{ item.repo }}"
    update_cache: yes
  with_items:
    - repo: "ppa:webupd8team/java"
    #- repo: "ppa:andrei-pozolotin/maven3"
    #- repo: "ppa:cwchien/gradle"

- name: Set debconf selections for Java
  debconf: name='oracle-java{{ oracle_java_version }}-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Workaround pre Ansible 2.2 to allow deb conf vtype seen
  shell: echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections

- name: Install Oracle Java {{ oracle_java_version }}
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - "oracle-java{{ oracle_java_version }}-installer"

- name: Ensure JAVA_HOME environment variable set
  lineinfile:
    dest: /etc/environment
    line: "JAVA_HOME={{ oracle_java_home }}"
    regexp: "^JAVA_HOME=.*$"