---

- name: Create mapr group
  group: name="{{mapr_client_group}}" system=yes gid="{{mapr_client_gid}}"

- name: Create mapr user
  user: name="{{mapr_client_user}}" groups="{{mapr_client_group}}" system=yes uid="{{mapr_client_uid}}" append=yes

- name: Ensure ssh dir present
  file: dest="{{ mapr_client_home }}/.ssh" state=directory mode="0755" owner="{{mapr_client_user}}" group="{{mapr_client_group}}"

- name: Ensure ssh key present
  template: src="id_rsa" dest="{{mapr_client_home}}/.ssh/id_rsa" owner="{{mapr_client_user}}" group="{{mapr_client_group}}" mode="0600"

- name: Ensure ssh public key present
  template: src="id_rsa.pub" dest="{{mapr_client_home}}/.ssh/id_rsa.pub" owner="{{mapr_client_user}}" group="{{mapr_client_group}}" mode="0644"

- name: Ensure ssh authorized key present
  template: src="id_rsa.pub" dest="{{mapr_client_home}}/.ssh/authorized_keys" owner="{{mapr_client_user}}" group="{{mapr_client_group}}" mode="0600"

- name: Add mapr user to sudoers
  lineinfile:
    line: "{{mapr_client_user}} ALL = (ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{mapr_client_user}}"
    regexp: "^{{mapr_client_user}}\\s+ALL.*"
    create: yes

- name: Ensure /etc/sudoers.d/{{mapr_client_user}} perms set to 0440
  file:
    dest: "/etc/sudoers.d/{{mapr_client_user}}"
    mode: "0440"